apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-with-quota
spec:
  selector:
    matchLabels:
      purpose: quota-demo
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 1
  template:
    metadata:
      labels:
        purpose: quota-demo
    spec:
      containers:
      - name: container-quota
        image: nginx

