apiVersion: v1
kind: Pod
metadata:
  name: pod-sleep-inf
spec:
  containers:
  - name: pod-sleep-inf
    image: alpine
    command:
    - sleep
    - inf
    resources:
      limits:
        memory: 100Mi
        cpu: 500m
      requests:
        memory: 100Mi
        cpu: 200 m
    volumeMounts:
    - name: some-storage
      mountPath: /mnt/data
  volumes:
  - name: some-storage
    emptyDir: {}