apiVersion: v1
kind: Pod
metadata:
  name: pod-with-toleration
spec:
  containers:
    - name: container
      image: alpine
      command: ["/bin/sh"]
      args: ["-c", "while true; do echo ${MY_ENV}; sleep 10; done"]
      env:
      - name: MY_ENV
        value: "hello from env"
  tolerations:
  - key: "sample-key"
    operator: "Equals"
    value: "sample-value"
    effect: "NoSchedule"