apiVersion: v1
kind: Pod
metadata:
  name: pod-with-secret
spec:
  volumes:
  - name: foo
    secret:
      secretName: mysecret
  containers:
    - name: task-pv-container
      image: nginx
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - name: foo
          mountPath: "/usr/share/nginx/html"
          readOnly: true