apiVersion: v1
kind: Pod
metadata:
  name: pod-with-configmap
  labels:
    app: pod-with-configmap
spec:
  containers:
  - name: container-with-configmap
    image: nginx
    ports:
      - containerPort: 80
        name: "http-server"
    volumeMounts:
    - name: config-map
      mountPath: "/usr/share/nginx/html"
      readOnly: true
  volumes:
  - name: config-map
    configMap:
      name: myconfigmap